### ISSUE TITLE
Method getSubscription stream-notify-logged add fields

### ISSUE THREAD

**Issue by AgustinNG** [inf3cti0n95/Rocket.Chat.RealTime.API.RxJS#60]
I see that methods accept params but the subscription stream-notify-logged method user-status requires field field, I don't see that it can be used.

[https://rocket.chat/docs/developer-guides/realtime-api/subscriptions/stream-notify-logged/](https://rocket.chat/docs/developer-guides/realtime-api/subscriptions/stream-notify-logged/)

<img width="1448" alt="Captura de pantalla 2020-04-28 a las 12 15 34" src="https://user-images.githubusercontent.com/28344533/80475955-030d2600-894a-11ea-8c22-87b26845d91b.png">

**Comment by chris-aeviator** [comment]
@AgustinNG could you please provide an example how you get the subscription to work?

I can perfectly fine send a message via 

![image](https://user-images.githubusercontent.com/11522213/90276972-0c70be80-de65-11ea-860d-787844e5c8fb.png)


and get 

```
{
  "msg": "ready",
  "subs": [
    "1597426365282"
  ]
}
```
but strangely when trying the same with `getSubscription(...).subscribe()`

![image](https://user-images.githubusercontent.com/11522213/90277142-5a85c200-de65-11ea-9309-b38341f7fdb0.png)


 it errors out since a string is required as the param ????

```
Exception from sub stream-livechat-room id 30ca7a52-5923-49bf-baa6-e49ffd999fb0 Error: Match error: Expected string, got object
    at check (packages/check/match.js:36:17)
    at Streamer._publish (packages/rocketchat:streamer/server/server.js:283:3)

```
```

**Comment by julienchabanon** [comment]
I got the same issue here
